defaults:
  - _self_
  - task: gear_mesh_vision_wrist_sideview

name: train_diffusion_policy_timm_visuomotor
_target_: diffusion_policy.workspace.train_diffusion_unet_image_workspace.TrainDiffusionUnetImageWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "timm_vit_2view_visuomotor"

policy:
  _target_: diffusion_policy.policy.diffusion_unet_timm_isaaclab_policy.DiffusionUnetTimmIsaacLabPolicy
  shape_meta: ${shape_meta}

  noise_scheduler:
    _target_: diffusers.DDIMScheduler
    num_train_timesteps: 50
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: epsilon

  obs_encoder:
    _target_: diffusion_policy.model.vision.timm_obs_encoder_with_force.TimmObsEncoderWithForce
    shape_meta: ${shape_meta}
    fuse_mode: modality-attention
    reduce_pretrained_lr: True

    vision_encoder_cfg:
      model_name: 'vit_base_patch32_clip_224.openai'
      pretrained: True
      frozen: False
      global_pool: ''
      feature_aggregation: null
      position_encoding: null
      downsample_ratio: 32
      transforms:
        - type: RandomCrop
          ratio: 0.9
      use_group_norm: True
      share_rgb_model: False
      imagenet_norm: True

    force_encoder_cfg: null

  num_inference_steps: 16
  diffusion_step_embed_dim: 32
  down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: True
  input_pertub: 0.1
  train_diffusion_n_samples: 1
  hack_no_obs_encoder_for_dense: False

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 8 # 64 for grad accum 1
  num_workers: 4
  shuffle: True
  pin_memory: True
  persistent_workers: True

val_dataloader:
  batch_size: 8 # 64 for grad accum 1
  num_workers: 4
  shuffle: False
  pin_memory: True
  persistent_workers: True

optimizer:
  _target_: torch.optim.AdamW
  lr: 8.0e-5
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: False
  lr_scheduler: cosine
  lr_warmup_steps: 1000  # 1000 for batch size 64
  num_epochs: 150
  gradient_accumulate_every: 8 # 1 for batch size 64
  use_ema: True
  freeze_encoder: False
  rollout_every: 10000
  checkpoint_every: 5
  val_every: 5
  sample_every: 5
  max_train_steps: null
  max_val_steps: null
  vram_log_every: 50
  tqdm_interval_sec: 1.0

logging:
  project: tactile-vla-diffusion
  resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: val_loss
    mode: min
    k: 7
    format_str: 'epoch={epoch:04d}-val_loss={val_loss:.4f}.ckpt'
  save_last_ckpt: False
  save_last_snapshot: False

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: logs/diffusion/${task_name}/${now:%Y.%m.%d-%H.%M.%S}
  sweep:
    dir: logs/diffusion/${task_name}/${now:%Y.%m.%d-%H.%M.%S}
    subdir: ${hydra.job.num}
