name: gear_mesh_vision_wrist_sideview

dataset_path: logs/vistac_rollouts/gear_mesh_200success_vistac_timmft_teacher397_fixedeef_fixedheight_8cm.h5

shape_meta: &shape_meta
  obs:
    wrist:
      shape: [3, 224, 224]
      type: rgb
    side_view:
      shape: [3, 224, 224]
      type: rgb
    state:
      shape: [8]
      type: low_dim
  action:
    shape: [6]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.isaaclab_hdf5_image_dataset.IsaacLabHdf5ImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  val_ratio: 0.1
  seed: 42
  max_train_episodes: null
  max_val_episodes: null
  image_crop_size: 224
  use_ft: false
  rotation_rep: raw
