name: gear_mesh_vision_wrist

dataset_path: logs/vision_rollouts/gear_mesh_500expert_demos_5dg.hdf5

shape_meta: &shape_meta
  obs:
    wrist:
      shape: [3, 256, 256]
      type: rgb
    state:
      shape: [8]
      type: low_dim
  action:
    shape: [6]

env_runner:
  _target_: diffusion_policy.env_runner.isaaclab_diffusion_image_runner.IsaacLabDiffusionImageRunner
  task_name: Visuomotor-Factory-GearMesh-Direct-v0
  num_envs: 8
  num_loops: 1
  device: ${training.device}
  use_fabric: true
  headless: true
  real_time: false
  random_orn: null
  image_crop_size: ${..dataset.image_crop_size}
  use_ft: ${..dataset.use_ft}

dataset:
  _target_: diffusion_policy.dataset.isaaclab_hdf5_image_dataset.IsaacLabHdf5ImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  val_ratio: 0.1
  seed: 42
  max_train_episodes: null
  max_val_episodes: null
  image_crop_size: 256
  use_ft: false
  rotation_rep: raw
