name: gear_mesh_vision_wrist

shape_meta:
  obs:
    wrist:
      shape: [3, 180, 180]
      type: rgb
    state:
      shape: [8]
      type: low_dim
  action:
    shape: [6]

dataset_path: logs/vision_rollouts/gear_mesh_500expert_demos_5dg.hdf5

dataset:
  val_ratio: 0.1
  max_train_episodes: 0
  max_val_episodes: 0
  state_action_normalization: limits
  image_normalization: zero_one
  image_crop_size: 180
  ft: false
